### ISSUE TITLE
Shares and Follwers

### ISSUE THREAD

**Issue by veenassit** [ttddyy/spring-social-slideshare-demo#1]
Hi 
Can we get total number of followers ,new followers and slide shares  from this code?

if yes could you please provide code details how to pull.

Thanks,
Veena

**Comment by ttddyy** [comment]
Hi @veenassit,

I don't think SlideShare provides followers and slide shares information via Rest API.
http://www.slideshare.net/developers/documentation

So, unfortunately, my answer is no.
